name = input('Type something: ')
print('The primitive type of this value is: {}'.format(type(name)))
print('Has only whitespaces? {}'.format(name.isspace()))
print("It's a number? {}".format(name.isnumeric()))
print('Is alphabetic? {}'.format(name.isalpha()))
print('Is alphanumeric? {}'.format(name.isalnum()))
print('Is upper case? {}'.format(name.isupper()))
print('Is lowercase? {}'.format(name.islower()))
print('Is a capitalized text? {}'.format(name.istitle()))
